program: tuning_rm_scand.py
method: bayes
metric:
  goal: minimize
  name: avg_val_loss
parameters:
  batch_size:
    values: [32, 64, 96]
  num_queries:
    values: [ 4, 8, 12 ]
  num_heads:
    values: [ 4, 8, 12 ]
  num_attn_stacks:
    values: [ 0, 1, 2 ]
  activation_type:
    values: ["relu", "gelu"]
  learning_rate:
    distribution: "log_uniform_values"
    min: 0.0001
    max: 0.01
  epochs:
    value: 5
  train_val_split:
    value: 0.8
  num_workers:
    value: 1
  save_model:
    value: False
  batch_print_freq:
    value: 10
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27
