_wandb:
    value:
        cli_version: 0.19.6
        code_path: code/src/training/train_rm_scand.py
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "6": 4.48.3
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_print_freq:
    value: 5
batch_size:
    value: 256
epochs:
    value: 200
hidden_dim:
    value: 768
learning_rate:
    value: 0.0008
num_queries:
    value: 4
num_workers:
    value: 4
save_model:
    value: true
train_val_split:
    value: 0.8
